# SWYFT Lightning configuration script - using Hydra
hydra:
        run:
                dir: ./
tensorboard:
        save_dir: ./lightning_logs
        name: "development"
        version:
simulation:
        model:
                _target_: simulators.Model
                bounds:
                        #   _target_: bounds.TorchBounds
                        #   filename: ...
        store:
                path: ./train_data.pt
                train_size: 1000
estimation:
        network:
                _target_: networks.UNet
        hparams:
        optimizer:
                _target_: torch.optim.Adam
                lr: 1e-3
        lr_scheduler:
                _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
                patience: 2
                factor: 0.1
        accelerator: gpu
        batch_size: 32
        max_epochs: 100
        early_stopping:
                min_delta: 0.
                patience: 10
        num_workers: 4
inference:
        interpreter:
                _target_: interpreters.interpret
        obs_path: ./Mock.pt
        bound: ./bound.pt
